### ISSUE TITLE
Add borders to the result table

### ISSUE THREAD

**Issue by cdjalel** [cdjalel/Zaid#1]

**Comment by haithemGuef** [comment]
@cdjalel 
About borders, what do you think of something like that, should i push it?

![image](https://user-images.githubusercontent.com/41695828/79688126-5c8b9b80-824c-11ea-8701-53f46a57412c.png)

**Comment by cdjalel** [comment]
Yes, that's good.  Go ahead & push it.
It would be nicer if you can merge the celles where inheritants share a part?
