### ISSUE TITLE
Asl al-massala is always 1 when all warathah are 3asabat

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#10]
in the book (الفرائض الميسر) page 40 (If warathah are all 3asabet, asl-al-massala is 3adad-ro2os), but the result in the app is always  1.
ex : only 3 alabna or 1 alabna and 1 albanat

![image](https://user-images.githubusercontent.com/41695828/79354999-6d32cd80-7f3d-11ea-8e33-1fbaf4c5417a.png)

![image](https://user-images.githubusercontent.com/41695828/79355165-9d7a6c00-7f3d-11ea-9e38-915c774b9c2a.png)

**Comment by cdjalel** [comment]
Nice catch :-)
The fix should be straightforward after line [976](https://github.com/cdjalel/Zaid/blob/master/app/src/main/java/com/djalel/android/zaid/Massala.java#L976)
if (!mFardh && mTa3seeb) {mAsl = mAdadRo2os;}

**Comment by haithemGuef** [comment]
I added the instructions block to the code, everything is fine, but (نصيب الفرد) on the screen is actually (نصيب عدد الرؤوس من نفس النوع).
I was exposed to the (نصيب الفرد) problem several times in some cases of shirka, i will put that later in issues.
can i push the modifications yet?

![image](https://user-images.githubusercontent.com/41695828/79458861-b8f37e80-7ff2-11ea-8e6a-74b73dfc96c2.png)

**Comment by cdjalel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [تصحيح الأخطاء الموُثقة في github](https://trello.com/c/Fc6TlHq1/24-%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A3%D8%AE%D8%B7%D8%A7%D8%A1-%D8%A7%D9%84%D9%85%D9%88%D9%8F%D8%AB%D9%82%D8%A9-%D9%81%D9%8A-github)
