### ISSUE TITLE
Bug in table of (المسألتين الغراوين)

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#11]
error in nassib alab and asl-al-massala in المسألتين الغراوين.

![image](https://user-images.githubusercontent.com/41695828/79364915-43cc6e80-7f4a-11ea-8a7f-9504fd4f1823.png)

![image](https://user-images.githubusercontent.com/41695828/79365152-868e4680-7f4a-11ea-8b03-ffbd55026ffa.png)

**Comment by cdjalel** [comment]
Indeed that's wrong.
The fix should be in the line [962](https://github.com/cdjalel/Zaid/blob/master/app/src/main/java/com/djalel/android/zaid/Massala.java#L962), where any Warith with Thuluth Albaqi should be excluded from the call to lcm(). i.e.

`if (m.isFardh() && !m.isTholuthAlbaqi()) {
`

**Comment by haithemGeuf** [comment]
I have added the instruction `&& !m.isTholuthAlbaqi()` to the test, but the error remains in asl-al-massala in the second case of (الغراوين) (alab, alom, azawj).

![image](https://user-images.githubusercontent.com/41695828/79455638-7a0efa00-7fed-11ea-9ed2-3b30ee59446a.png)

**Comment by haithemGuef** [comment]
I added the instruction `&& !m.isTholuthAlbaqi()` in the test, but the error remains in asl-al-massala in the second case of (الغراوين) (alab, alom, azawj).

![image](https://user-images.githubusercontent.com/41695828/79456572-053cbf80-7fef-11ea-8017-979313056af3.png)

**Comment by cdjalel** [comment]
Hmmm. My bad.
The test should be in the hissabAshomAndBaqi and not in hissabAsl around line 982,
 ```
            if (m.isFardh()) {
               if (m.isTholuthAlbaqi()) {
                    m.setFardh(0);    // if it is already zero? remove this line
                   continue;
               }
                int fardh = m.getBast() * mAsl / m.getMaqam();
                m.setFardh(fardh);
                mAshom += fardh;
            }
```
Try this fix. If it works merge it with the Jaddat one. But in separate commits.

**Comment by haithemGuef** [comment]
I tried it, it doesn't work, there are three problems, the first in calculating asl-massala, and the second in subtracting one third (1/3) of alom from baqi, the father has all baqi (الباقي), the third is nassib alom not (1/3) but always 1.

**Comment by cdjalel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [تصحيح الأخطاء الموُثقة في github](https://trello.com/c/Fc6TlHq1/24-%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A3%D8%AE%D8%B7%D8%A7%D8%A1-%D8%A7%D9%84%D9%85%D9%88%D9%8F%D8%AB%D9%82%D8%A9-%D9%81%D9%8A-github)
