### ISSUE TITLE
aljadat take a 1/6 each one, iso of sharing it 

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#13]
when we have 2 jadat in warathah, we divide a sixth (1/6) between them (يشتركن بالتساوي في السدس).

ex (2 aljadat, 1 alabna): asl = 6,  aljadat takes 1 from 6, and alabna 5 (الباقي).
 but in the app each jaddah takes a sixth (1/6).

![image](https://user-images.githubusercontent.com/41695828/79463812-987af280-7ff9-11ea-8a0d-69210586d70b.png)

**Comment by cdjalel** [comment]
Confirmed.
The fix should be in three places:
1. add a getter isJada() in the Mirath class
2. in hissabAshomAnAlbaqi, around line [982](https://github.com/cdjalel/Zaid/blob/master/app/src/main/java/com/djalel/android/zaid/Massala.java#L982) of Massala.hava   
The if block inside the loop should skip the incrementation of mAshom for the second jadda.
bool counted = false;
for (Mirath m : mWarathah) {
            if (m.isFardh()) {
                int fardh = m.getBast() * mAsl / m.getMaqam();
                m.setFardh(fardh); 
               if (m.isJada()) {
                     if (counted) { continue; }
                     counted = true;
               }
                mAshom += fardh;
            }
  }
