### ISSUE TITLE
الأخت التي ترث بالتعصيب مع الغير تصبح كالأخ، فيجب أن تحجب من يحجبه الأخ : أنباء الإخوة، والأعمام وأبناؤهم.

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#14]
في حالة وجود ابن أخ الشقيق مع أخت شقيقة أو لأب عاصبة مع الغير، فابن الأخ يكون محجوبا بالشقيقة أو الأخت لأب حجب حرمان عند كونها عاصبة مع الغير
كذلك ابن الأخ لأب مع الأخت لأب والشقيقة العاصبة مع الغير،
والأخ لأب مع الشقيقة العاصبة مع الغير

ex: (albanat 1, ashakikat 1, abna alikhwa alashika 1): ibn alakh becomes mahjoub.

![image](https://user-images.githubusercontent.com/41695828/79467743-6ddf6880-7ffe-11ea-85d8-3f3efd391c26.png)

**Comment by cdjalel** [comment]
OK. This means all the Hajb cased need be checked systematically.
So please got through the Hajb tabe in page 36 of the book "الفرائض المُيسر" and start from the second column. 
Each hte mirath.... method of each Hajib should be checked to see if the person of the first column, the Mahjoob, is present in the code with the proper call to addHajb. 
If not, please add it.

**Comment by cdjalel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [تصحيح الأخطاء الموُثقة في github](https://trello.com/c/Fc6TlHq1/24-%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A3%D8%AE%D8%B7%D8%A7%D8%A1-%D8%A7%D9%84%D9%85%D9%88%D9%8F%D8%AB%D9%82%D8%A9-%D9%81%D9%8A-github)
