### ISSUE TITLE
bug in test of method mirathAla3mamLiAb()

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#16]
at the line 917 of massala.java the `&&`  after alikhwa_wa_abna_alikhwa should be `||`
`if ((nbr == 0) || far3_wa_asl_warith_dhaker || alikhwa_wa_abna_alikhwa && (mInput.get_ala3mam_alashika() > 0)) return;`

sorry I don't know how to link the line to the issue

**Comment by cdjalel** [comment]
to link the line just write its number, select it and click the link button in the bar pf editor (above). Then paste the link between () in place of the word URL. The link itself you can get it from reading the code inside github.

**Comment by cdjalel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [تصحيح الأخطاء الموُثقة في github](https://trello.com/c/Fc6TlHq1/24-%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A3%D8%AE%D8%B7%D8%A7%D8%A1-%D8%A7%D9%84%D9%85%D9%88%D9%8F%D8%AB%D9%82%D8%A9-%D9%81%D9%8A-github)
