### ISSUE TITLE
إختيار الأفضل للجد في حالة الجد والإخوة مع انعدام أصحاب الفروض

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#28]
إذا لم يكن مع الجد والإخوة صاحب فرض يأخذ الجد الأفضل بين (ثلث المال أو المقاسمة).
- إذا كان الإخوة أقل من مثليه تكون المقاسمة أحظ له.
- إذا كان الإخوة أكثر من مثليه يكون ثلث المال أحظ له.
- إذا كان الإخوة مثليه يستوي الثلث والمقاسمة.
الفرائض الميسر ص 45.

**Comment by cdjalel** [comment]
Done in all commits of Apr 25, 2020. (Forgot to put hte issue # in the commits messages)
