### ISSUE TITLE
إختيار الأفضل للجد في حالة الجد والإخوة مع وجود أصحاب فرض

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#29]
إذا كان مع الجد والإخوة صاحب فرض يأخذ الجد الأفضل بين (ثلث المال أو المقاسمة أو السدس).

إن بقي بعد أصحاب الفروض أكثر من السدس أخذ الجد الأفضل من
- سدس جميع المال.
- ثلث باقي المال بعد أصحاب الفروض.
- المقاسمة. 

إن بقي بعد أصحاب الفروض أقل من السدس أو لم يبق شيء فرض السدس للجد وسقط الإخوة.

**Comment by cdjalel** [comment]
Done in all commits of Apr 25, 2020. (Forgot to put hte issue # in the commits messages)
