### ISSUE TITLE
move aljad before alakhawat when they inherits instead of brothers

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#33]
move aljad before alakhawat when they inherits instead of brothers (بالتعصيب عند وجود بنت) 

![image](https://user-images.githubusercontent.com/41695828/80012997-789e6f80-84ce-11ea-9f5b-7f68d4b64ec1.png)

**Comment by cdjalel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [تصحيح الأخطاء الموُثقة في github](https://trello.com/c/Fc6TlHq1/24-%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A3%D8%AE%D8%B7%D8%A7%D8%A1-%D8%A7%D9%84%D9%85%D9%88%D9%8F%D8%AB%D9%82%D8%A9-%D9%81%D9%8A-github)
