### ISSUE TITLE
Replace getName with getSharhPrefix in some mirath methods

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#6]
replace `getName(nbr)` with `getSharhPrefix(nbr)` in sharh of mirath of:

- abna_alikhwa_alashika
- abna_alikhwa_li_ab
- ala3mam_alashika
- ala3mam_li_ab
- abna_ala3mam_alashika
- abna_ala3mam_li_ab

**Comment by cdjalel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [تصحيح الأخطاء الموُثقة في github](https://trello.com/c/Fc6TlHq1/24-%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A3%D8%AE%D8%B7%D8%A7%D8%A1-%D8%A7%D9%84%D9%85%D9%88%D9%8F%D8%AB%D9%82%D8%A9-%D9%81%D9%8A-github)
