### ISSUE TITLE
Bug in sharh of mirath aljad (textual form)

### ISSUE THREAD

**Issue by haithemGuef** [cdjalel/Zaid#7]
In the case of mirath aljad when `far3_warith_ontha` is present, and no `far3_warith_dhakar` and no `alikhwa_alashika_wa_li_ab` .

The bug has been fixed.

**Comment by cdjalel** [comment]
Describe a usecase where this fails. i.e. an example of Mass2ala that shows the problem.

**Comment by cdjalel** [comment]
See comments of isseu [#6](https://github.com/cdjalel/Zaid/issues/6)

Ideally each issue should describe one problem only. Issue #6 describes two.

**Comment by cdjalel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [تصحيح الأخطاء الموُثقة في github](https://trello.com/c/Fc6TlHq1/24-%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD-%D8%A7%D9%84%D8%A3%D8%AE%D8%B7%D8%A7%D8%A1-%D8%A7%D9%84%D9%85%D9%88%D9%8F%D8%AB%D9%82%D8%A9-%D9%81%D9%8A-github)
